export Peoples              from './peoples.js'
export HomeScene            from './HomeScene.js'
export DetailsScene         from './DetailsScene.js'
export ProductScene         from './ProductScene.js'
export ProductDetailsScene  from './ProductDetailsScene.js'
export UserScene            from './UserScene.js'
export NewsScene            from './NewsScene.js'
export NewsDetailsScene     from './NewsDetailsScene.js'
